### ISSUE TITLE
Clamp small values to destination

### ISSUE THREAD

**Issue by Bkucera** [arqex/react-interactable#3]
It would be nice to clamp transform values to pixel-perfect numbers to avoid setting a transform like: `translateY(-0.0711994px)`, which could throw off text aliasing and make fonts appear blurry

**Comment by arqex** [comment]
Hey Ben,

Thanks for your interest in the library, and sorry for being so unresponsive, it's hard to me to find time for the open-source projects! The thing is I love r-interactable, and I am planning to use it in a side project soon, so I'll try to keep it updated!

Clamping values sounds like a great idea! It's been a while since I don't have a look at the source code, but I think the best way of doing it is just before rendering out as transforming props, because those decimal numbers are precious at calculation time of the animations.

Feel free to give it a try at the changes needed, otherwise it will take me a little to start adding them myself.

Would you be interested in being a maintainer of the project? I think it has a big potential but I have never had time to promote it as it deserves, having another couple of hands and eyes would be great!
